import { Dimensions, StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  header: {
    backgroundColor: COLORS.PRIMARY100,
    height: 80,
    elevation: 1,
    shadowColor: COLORS.BLACK,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    justifyContent: "center",
    alignItems: "baseline",
  },
  container: {
    alignSelf: "center",
    backgroundColor: "#FAFBFC",
    flex: 1,
    width: Dimensions.get("window").width,
    minWidth: 300,
    maxWidth: 1200,
    height: Dimensions.get("window").height,
    alignItems: "baseline",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 20,
  },
  smallContainer: {
    alignSelf: "center",
    backgroundColor: "#FAFBFC",
    flex: 1,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    flexDirection: "column",
  },
  smallLeftContainer: {
    width: Dimensions.get("window").width * 0.9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDEFF2",
    alignItems: "center",
    alignSelf: "center",
    margin: 12,
    marginTop: 80,
  },

  smallRightContainer: {
    width: Dimensions.get("window").width * 0.95,
    borderRadius: 8,
    alignSelf: "center",
    margin: 16,
  },
  leftContainer: {
    width: "30%",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDEFF2",
    alignItems: "center",
    alignSelf: "flex-start",
    margin: 16,
    marginTop: 100,
  },
  rightContainer: {
    marginTop: 50,
    width: "60%",
    padding: 16,
  },
  formContainer: {
    backgroundColor: "white",
    padding: 16,
    borderRadius: 8,
    width: "100%",
  },
  input: {
    width: "100%",
    padding: 8,
    marginVertical: 8,
    borderWidth: 1,
    backgroundColor: "white",
    borderColor: "#F2F3F6",
    borderRadius: 8,
    color: "grey",
  },

  name: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#4F5F80",
  },
  title: {
    fontWeight: "bold",
    color: "#4F5F80",
    fontSize: 20,
    textAlign: "left",
    alignSelf: "baseline",
    marginBottom: 8,
  },
  pressable: {
    width: "100%",
    height: 42,
    backgroundColor: "#2D70FD",
    borderWidth: 1,
    borderColor: "#F2F3F6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginTop: 10,
  },
  disabled: {
    opacity: 0.5,
  },
  image: {
    height: 50,
    width: 50,
    marginLeft: 10,
    resizeMode: "contain",
  },
  actionButton: { marginHorizontal: 16 },
  inputContainer: {
    width: "100%",
    height: "100%",
    paddingHorizontal: 16,
  },
  smallInputContainer: {
    flexDirection: "row",
    width: "100%",
    paddingHorizontal: 16,
    justifyContent: "space-between",
  },
});
