import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    alignSelf: "center",
    backgroundColor: "#FAFBFC",
    flex: 1,
    width: Dimensions.get("window").width,
    minWidth: 300,
    maxWidth: 1200,
    height: Dimensions.get("window").height,
    alignItems: "baseline",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 20,
  },
  midContainer: {
    alignSelf: "center",
    backgroundColor: "#FAFBFC",
    flex: 1,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    flexDirection: "column",
  },
  midLeftContainer: {
    width: Dimensions.get("window").width * 0.9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDEFF2",
    alignItems: "center",
    alignSelf: "center",
    margin: 16,
    marginTop: 100,
  },
  midFormContainer: {
    backgroundColor: "white",
    padding: 8,
    borderRadius: 8,
    width: "100%",
  },
  midRightContainer: {
    width: Dimensions.get("window").width * 0.9,
    borderRadius: 8,
    alignSelf: "center",
    margin: 16,
  },
  smallContainer: {
    alignSelf: "center",
    backgroundColor: "#FAFBFC",
    flex: 1,
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
    flexDirection: "column",
  },
  smallLeftContainer: {
    width: Dimensions.get("window").width * 0.9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDEFF2",
    alignItems: "center",
    alignSelf: "center",
    margin: 12,
    marginTop: 80,
  },
  smallFormContainer: {
    backgroundColor: "white",
    padding: 8,
    borderRadius: 8,
    width: "100%",
  },
  smallRightContainer: {
    width: Dimensions.get("window").width * 0.95,
    borderRadius: 8,
    alignSelf: "center",
    margin: 16,
  },
  leftContainer: {
    width: "30%",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#EDEFF2",
    alignItems: "center",
    alignSelf: "flex-start",
    margin: 16,
    marginTop: 100,
  },
  rightContainer: {
    marginTop: 50,
    width: "60%",
    padding: 16,
  },
  formContainer: {
    backgroundColor: "white",
    padding: 16,
    borderRadius: 8,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    width: "100%",
    padding: 8,
    marginVertical: 8,
    borderWidth: 1,
    backgroundColor: "white",
    borderColor: "#F2F3F6",
    borderRadius: 8,
    color: "grey",
  },

  name: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#4F5F80",
  },

  pressable: {
    width: "100%",
    height: 42,
    backgroundColor: "#2D70FD",
    borderWidth: 1,
    borderColor: "#F2F3F6",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    marginTop: 10,
  },
  disabled: {
    opacity: 0.5,
  },
  image: {
    height: 50,
    width: 50,
    marginLeft: 10,
    resizeMode: "contain",
  },
});
